### PR TITLE
Test on currently supported versions of CPython

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
What is this?

**Comment by cclauss** [comment]
A synchronization with https://devguide.python.org/#branchstatus

**Comment by tapaswenipathak** [comment]
I don't like that, that the features/ideas that are being implemented are only for CPython supported Python version. The exciting spin is my project would independently automate everything Travis continuous integration. I just feel Travis can be fully automated running w/o any human intervention  and few interns are implementing for/with me. I would support as many Python versions as can be, I hope it will be useful, appreciate the effort, closing.

**Comment by cclauss** [comment]
> I don't like that, that the features/ideas that are being implemented are only for CPython supported Python version.

Correct.  This PR was meant to support all versions that the Python Core Team supports by adding Python 3.7 and by dropping all https://devguide.python.org/devcycle/#end-of-life-branches

Might be worth looking at https://github.blog/2019-08-08-github-actions-now-supports-ci-cd which is currently in Beta and will release in November.  This would enable your team's work to run right inside GitHub.

**Pull request closed without merging**
