### PR TITLE
Add Python 3.7

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Appreciate the effort. Why only 3.7? My goal is properly exposing everything Python version `x.x` from https://www.python.org/doc/versions/.

**Comment by cclauss** [comment]
There are two ways to install a Python instance in Travis CI.
1. __python: x.y__  # This list changed this week when Xenial became the default distro for Travis
2. The list of Pythons in __pyenv install --list__  # This is slow but more complete

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Hey @cclauss: Thanks for being super fast and for the effort. :)

I am on a vacation, at the exact minute capturing Delhi's street life.

Meanwhile I would suggest you do a research on how you can have Ubuntu Cosmic in .travis.yml. As said, I want all Python versions fully supported.

**Comment by cclauss** [comment]
Enjoy your vacation -- no rush on any of this.  Delhi is magical!

__dist: bionic__ easy but __dist: cosmic__ no: https://docs.travis-ci.com/user/reference/overview

**Comment by tapaswenipathak** [comment]
Thanks! Live update I am at a signal rn. :) I get quite a few number of emails and respond as quickly as I can, otherwise I forget. Do you know Docker? With computers there is no, no. Please only have Ubuntu Cosmic and all Python versions supported - https://docs.travis-ci.com/user/docker/ 

Appreciate your effort.

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Thanks! Live update I am at a signal rn. :) I get quite a few number of emails and respond as quickly as I can, otherwise I forget. Do you know Docker? With computers there is no, no. Please only have Ubuntu Cosmic and all Python versions supported - https://docs.travis-ci.com/user/docker/ 

Appreciate your effort.

**Comment by cclauss** [comment]
Yup https://github.com/cclauss/Python2-and-Python3-in-Docker

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Please don't open bogus PRs, keep in draft state and ask questions if you don't know how you can do X, closing.

**Comment by cclauss** [comment]
> My goal is properly exposing everything Python version x.x from
> https://www.python.org/doc/versions/.

**Pull request closed without merging**
