### PR TITLE
Travis multi os support

### PR DESCRIPTION
**Pull request by sourabhpruthi10**
Ref #3

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
lol what is this?

**Comment by sourabhpruthi10** [comment]
@tapaswenipathak actually i  thought you want me to add travis file on this project to run on different os

**Comment by sourabhpruthi10** [comment]
i think i need to add these to various .travis.yml files inside language directories

**Comment by tapaswenipathak** [comment]
If you are interested in working on the project let me know how I can
be useful. This is quite complex. I have written few things
https://github.com/tapaswenipathak/Internship/issues/43. I will write
few more things on the ticket.



--
Tapasweni

**Review by tapaswenipathak — COMMENTED** [review]
Thanks for putting the effort, please work on the ticket after I write.

**Pull request closed without merging**
