### PR TITLE
Add code files

### LINKED ISSUE #10: Add code files per programming language
dep https://github.com/tapaswenipathak/Travis-CI/issues/1.

- [ ] C
- [ ] C++
- [ ] Generic
- [ ] Java
- [ ] JS
- [ ] Perl
- [ ] PHP
- [ ] Python

### PR DESCRIPTION
**Pull request by kurianbenoy**
Fix #10

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Django app? Please add a commit per programming language. Make sure `.travis.yml` are running on the code files.

**Comment by kurianbenoy** [comment]
Ok, then is a simple hello world program required?. I added Django web app, because in .travis.yml of Python, its needed to have requirements.txt.

Can you suggest any alternative code then?

**Comment by kurianbenoy** [comment]
>Make sure `.travis.yml` are running on the code files.
I am curious if the Travis for this repo is activated or not? 
https://travis-ci.org/tapaswenipathak/Travis-CI

Can you confirm @tapaswenipathak , as far as I know I can't manually test whether the travis test is passing or not. Am I saying the same thing you wanted me to do?

**Review by tapaswenipathak — COMMENTED** [review]
Nope. Running Travis and Django app, no, foolish thing. Have Python file, write function `hello world`, add a functional test. In `.travis.yml` run `script: - pytest`. Deploy and whoosh.

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
- In GCC, Clang compilers `void main()` is invalid. Please write `int main()` in C program.
- Please write proper Java program enabling Travis file.
- The nodejs program is invalid as well running on Travis. Please enable Travis then submit.
- Did the Perl program ran when you enabled Travis? 
- Did the PHP ran when you enabled Travis?
- Please write proper Python program as I suggested.

**Review by tapaswenipathak — COMMENTED** [review]
- C code file is still incorrect
- nodejs file won't run on Travis
- Python script needs a test
- php file needs a phpunit

Did you run these on Travis CI? Let me know if you need help.

**Pull request merged**
